local res = {}
res.image = {
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
	{'climber', 'media/images/left-hand-climber-hi.png' },
}
return res
